# Generated by Django 2.2 on 2019-06-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190603_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforms',
            name='presentation',
            field=models.TextField(),
        ),
    ]
