# Generated by Django 2.2 on 2019-06-01 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_topic_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='thinker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='board', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
