# Generated by Django 2.2 on 2019-06-04 05:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=tinymce.models.HTMLField(max_length=4000, verbose_name='Content'),
        ),
    ]
